package parameters

import "fmt"

//   Parameter Name:  RANGE
//
//   Purpose:  To specify the effective range of recurrence instances from
//      the instance specified by the recurrence identifier specified by
//      the property.
//
//   Format Definition:  This property parameter is defined by the
//      following notation:
//       rangeparam = "RANGE" "=" "THISANDFUTURE"
//       ; To specify the instance specified by the recurrence identifier
//       ; and all subsequent recurrence instances.
//
//   Description:  This parameter can be specified on a property that
//      specifies a recurrence identifier.  The parameter specifies the
//      effective range of recurrence instances that is specified by the
//      property.  The effective range is from the recurrence identifier
//      specified by the property.  If this parameter is not specified on
//      an allowed property, then the default range is the single instance
//      specified by the recurrence identifier value of the property.  The
//      parameter value can only be "THISANDFUTURE" to indicate a range
//      defined by the recurrence identifier and all subsequent instances.
//      The value "THISANDPRIOR" is deprecated by this revision of
//      iCalendar and MUST NOT be generated by applications.
//
//   Example:
//
//       RECURRENCE-ID;RANGE=THISANDFUTURE:19980401T133000Z

type RecurrenceIdRange struct {
	V string
}

var ThisAndFuture = RecurrenceIdRange{"THISANDFUTURE"}

func (r *RecurrenceIdRange) Parameter() string {
	return fmt.Sprintf("RANGE=%s", r.V)
}
